### ISSUE TITLE
[ENTREGA Recuperatorio de Objetos] Christian Merciú

### ISSUE THREAD

**Issue by ChrisMerciu** [pdep-lunes-tarde/2024-objetos-recuperatorio-1-ChrisMerciu#1]
Juan Fernandes @juanFdS

**Comment by JuanFdS** [comment]
## Parte A
### Punto 1
⚠ ¿Por qué los amuletos y la ojota tienen un método `poderBase()` si no tienen poder base? Los objetos sólo deberían entender los mensajes que tengan sentido según el dominio.
⚠️ El modelado de las rarezas de túnicas tiene inconsistencias. Hay una clase `Rareza` que tiene una variable interna `rareza`, luego heredan de ella dos objetos que tienen como `rareza` a sí mismos y no usan esta variable. No veo por qué no podría modelarse como dos objetos que compartan un mensaje en común.
⚠️ Hay lógica repetida entre las dos rarezas de túnicas. Parece que hay comportamiento de las túnicas en general y luego un extra acorde a si es común o épica.
Salvo por esos detalles, está bien ✅
### Punto 2
❌ Los métodos `esVencido` de las categorías tienen tipos de retorno distintos (a veces booleanos, a veces números) y lo que se evalúa dentro del if en las primeras dos no se utiliza. Por cómo está escrito, los magos aprendices y veteranos siempre son vencidos, lo cual no es cierto; y en el caso de los inmortales se intentará sumar un booleano a un número, lo cual no tiene sentido.
⚠️ En el método `desafiar(otroMago)` se rompe el encapsulamiento del mago, deberían haber métodos más declarativos como `esVencido` (en la clase Mago, es decir, que el mago pueda contestar si otro lo vence o no) y `energiaPerdidaAlSerVencido`, o similares.
## Parte B
### Punto 1
❌ No implementado.
### Punto 2
❌ Incompleto.
### Punto 2
No implementado.
## Tests
No son exhaustivos para la parte testeada, por lo que no suman puntaje adicional.

Nota: 3.
